# @package task

name: ??? # Must be overridden by the specific task (e.g., G1TrackSuitcase)

viewer:
  resolution: [2560, 1440]
  lookat: [0., 0., 0.]
  eye: [4.0, 4.0, 4.0]
  env_spacing: 3.0

terrain: plane

num_envs: 4096
max_episode_length: 1000

sim:
  step_dt: 0.02
  isaac_physics_dt: 0.005
  mujoco_physics_dt: 0.002

robot:
  name: ???
  robot_type: ???

action:
  _target_: active_adaptation.envs.mdp.action.JointPosition
  action_scaling:
    .*: 0.25
  min_delay: 2
  max_delay: 6
  alpha: [0.8, 1.0]

command:
  _target_: active_adaptation.envs.mdp.commands.hdmi.command.RobotObjectTracking
  data_path: ???             # Must be overridden

  # Isaac Link Idx
  tracking_keypoint_names: [
    "hip_(pitch|yaw)_.*_link",    # G1: ".*_hip_(pitch|yaw)_link",
    "knee_pitch_.*_link",         # G1: ".*_knee_link",
    "ankle_roll_.*_link",         # G1: ".*_ankle_roll_link",
    "pelvis",                     # G1: "pelvis"
    "body_yaw_link",              # G1: "torso_link",
    "head_roll_link",             # head tracking 추가
    "shoulder_pitch_.*_link",     # G1: ".*_shoulder_pitch_link",
    "elbow_yaw_.*_link",          # G1: ".*_elbow_link",
    "wrist_roll_.*_link",         # G1: ".*_wrist_yaw_link"
  ]

  # Isaac Joint Idx
  tracking_joint_names: [
      "body_yaw_joint",           # G1: "waist_.*_joint",
      "head_.*_joint",            # head tracking 추가
      "hip_.*_joint",             # G1: ".*_hip_.*_joint",
      "knee_pitch_.*_joint",      # G1: ".*_knee_joint",
      "ankle_.*_joint",           # G1: ".*_ankle_.*_joint",
      "shoulder_.*_joint",        # G1: ".*_shoulder_.*_joint",
      "elbow_pitch_.*_joint",     # G1: ".*_elbow_joint"
  ]

  root_body_name: ???

  pose_range:
    x: [-0.05, 0.05]
    y: [-0.05, 0.05]
    z: [-0.01, 0.01]
    roll: [-0.1, 0.1]
    pitch: [-0.1, 0.1]
    yaw: [-0.2, 0.2]

  velocity_range:
    x: [-0.2, 0.2]
    y: [-0.2, 0.2]
    z: [-0.2, 0.2]
    roll: [-0.5, 0.5]
    pitch: [-0.5, 0.5]
    yaw: [-0.5, 0.5]

  init_joint_pos_noise: 0.1
  init_joint_vel_noise: 0.1

  future_steps: [1, 2, 8, 16, 32]

  extra_object_names: []
  # the one that is used for tracking
  object_asset_name: ???     # Must be overridden (e.g., "suitcase")
  object_body_name: ???      # Must be overridden (e.g., "suitcase")

  object_pose_range:
    x: [-0.05, 0.05]
    y: [-0.05, 0.05]
    z: [-0.01, 0.01]
    roll: [-0.1, 0.1]
    pitch: [-0.1, 0.1]
    yaw: [-0.1, 0.1]

  contact_target_pos_offset: ???  # Must be overridden
  contact_eef_body_name: ["wrist_roll_l_link", "wrist_roll_r_link"] # G1: ["left_wrist_yaw_link", "right_wrist_yaw_link"]
  contact_eef_pos_offset:
    - [0.0, 0.0, 0.0]
    - [0.0, 0.0, 0.0]

enable_cameras: false
camera_width: 160
camera_height: 120

# Common Observation section
observation:
  command:
    ref_body_pos_future_local: {}
    ref_joint_pos_future:      {}
    ref_motion_phase:          {}

  policy:
    root_ang_vel_history:      {history_steps: [0], noise_std: 0.05}
    projected_gravity_history: {history_steps: [0], noise_std: 0.05}
    joint_pos_history:         {history_steps: [0, 1, 2, 3, 4, 8], noise_std: 0.015}
    prev_actions:              {steps: 3}

  object:
    object_xy_b:               {noise_std: 0.01, episodic_noise_std: 0.0}
    object_heading_b:          {noise_std: 0.01, episodic_noise_std: 0.0}
    ref_contact_pos_b:         {noise_std: 0.01, episodic_noise_std: 0.02, yaw_only: true}

  depth:
    depth_camera:              {camera_name: "tiled_camera"}

  priv:
    root_ang_vel_history:      {history_steps: [0, 1, 2, 3, 4, 5, 6, 7, 8], noise_std: 0.0}
    projected_gravity_history: {history_steps: [0, 1, 2, 3, 4, 5, 6, 7, 8], noise_std: 0.0}
    joint_pos_history:         {history_steps: [0, 1, 2, 3, 4, 5, 6, 7, 8], noise_std: 0.0}

    ref_root_pos_future_b: {}
    ref_root_ori_future_b: {}

    diff_body_pos_future_local: {}
    diff_body_ori_future_local: {}
    diff_body_lin_vel_future_local: {}
    diff_body_ang_vel_future_local: {}

    root_linvel_b:    {}
    body_pos_b:       {body_names: "ankle_roll_.*_link"}                                # G1: ".*ankle_roll_link"
    body_vel_b:       {body_names: "ankle_roll_.*_link"}                                # G1: ".*ankle_roll_link"
    body_height:      {body_names: ["ankle_roll_.*_link", "pelvis", "body_yaw_link"]}   # G1: ".*ankle_roll_link", "pelvis", "torso_link"

    applied_action:   {}
    applied_torque:   {}

    object_pos_b:     {}
    object_ori_b:     {}
    diff_object_pos_future: {}
    diff_object_ori_future: {}

    ref_object_contact_future: {}
    diff_contact_pos_b:        {}

  ref_joint_pos_:
    ref_joint_pos_action_policy: {}

# Common Reward section
reward:
  # 1) Deep-Mimic based Robot Tracking
  tracking:
    tracking_upper_body_pos(keypoint_pos_tracking_local_product):
      body_names: ["head_roll_link", "shoulder_pitch_.*_link", "elbow_yaw_.*_link", "wrist_roll_.*_link"]    # G1: ".*_shoulder_pitch_link", ".*_elbow_link", ".*_wrist_yaw_link"
      weight: 0.5
      sigma: 0.5

    tracking_upper_body_ori(keypoint_ori_tracking_local_product):
      body_names: ["head_roll_link", "shoulder_pitch_.*_link", "elbow_yaw_.*_link", "wrist_roll_.*_link"]    # G1: ".*_shoulder_pitch_link", ".*_elbow_link", ".*_wrist_yaw_link"
      weight: 0.5
      sigma: 1.0

    tracking_lower_body_pos(keypoint_pos_tracking_local_product):
      body_names: ["hip_pitch_.*_link", "knee_pitch_.*_link", "ankle_roll_.*_link"]       # G1: ".*_hip_pitch_link", ".*_knee_link", ".*_ankle_roll_link"
      weight: 1 #0.5
      sigma: 0.4

    tracking_lower_body_ori(keypoint_ori_tracking_local_product):
      body_names: ["hip_pitch_.*_link", "knee_pitch_.*_link", "ankle_roll_.*_link"]       # G1: ".*_hip_pitch_link", ".*_knee_link", ".*_ankle_roll_link"
      weight: 0.5
      sigma: 1.0

    tracking_root_pos(keypoint_pos_tracking_product):
      body_names: ["pelvis"]    # G1: "pelvis"
      weight: 0.5
      sigma: 0.5

    tracking_root_ori(keypoint_ori_tracking_product):
      body_names: ["pelvis"]    # G1: "pelvis"
      weight: 0.5
      sigma: 0.5

    tracking_body_linvel(keypoint_lin_vel_tracking_product):
      body_names: ["pelvis", "hip_yaw_.*_link", "knee_pitch_.*_link", "ankle_roll_.*_link", "body_yaw_link", "shoulder_pitch_.*_link", "elbow_yaw_.*_link", "wrist_roll_.*_link"]  # G1: "pelvis", ".*_hip_yaw_link", ".*_knee_link", ".*_ankle_roll_link", "torso_link", ".*_shoulder_pitch_link", ".*_elbow_link", ".*_wrist_yaw_link"
      weight: 0.5
      sigma: 0.5

    tracking_body_angvel(keypoint_ang_vel_tracking_product):
      body_names: ["pelvis", "hip_yaw_.*_link", "knee_pitch_.*_link", "ankle_roll_.*_link", "body_yaw_link", "shoulder_pitch_.*_link", "elbow_yaw_.*_link", "wrist_roll_.*_link"]  # G1: "pelvis", ".*_hip_yaw_link", ".*_knee_link", ".*_ankle_roll_link", "torso_link", ".*_shoulder_pitch_link", ".*_elbow_link", ".*_wrist_yaw_link"
      weight: 0.5
      sigma: 2.5

    joint_pos_tracking_product:
      joint_names: ["body_yaw_joint", "head_.*_joint", "hip_.*_joint", "knee_pitch_.*_joint", "shoulder_.*_joint", "elbow_pitch_.*_joint"]  # G1: "waist_.*_joint", ".*_hip_.*_joint", ".*_knee_joint", ".*_shoulder_.*_joint", ".*_elbow_joint"
      weight: 0.5
      sigma: 0.25

    joint_vel_tracking_product:
      joint_names: ["body_yaw_joint", "head_.*_joint", "hip_.*_joint", "knee_pitch_.*_joint", "shoulder_.*_joint", "elbow_pitch_.*_joint"]  # G1: "waist_.*_joint", ".*_hip_.*_joint", ".*_knee_joint", ".*_shoulder_.*_joint", ".*_elbow_joint"
      weight: 0.5
      sigma: 2.5

  # 2) Object Tracking & INteraction
  object_tracking:
    # _multiplicative: true
    object_pos_tracking: {weight: 1.0, sigma: 0.5}
    object_ori_tracking: {weight: 1.0, sigma: 0.5}
    eef_contact_exp:     {weight: 1.0, enabled: true, pos_sigma: 0.3, frc_sigma: 40.0, frc_thres: 10.0, gain: 5.0}
  
  # 3) Regularization Penalties
  loco:
    action_rate_l2:     {weight: 0.1, enabled: true}
    joint_vel_l2:       {weight: 5.0e-4, enabled: true, joint_names: .*}
    joint_pos_limits:   {weight: 10.0, joint_names: ".*", soft_factor: 0.9, enabled: true}
    joint_torque_limits: {weight: 0.01, enabled: true, soft_factor: 0.6}
    survival:           {weight: 1.0, enabled: true}
  
  feet:
    impact_force_l2:    {weight: 1.0, enabled: true, body_names: ankle_roll_.*_link}                                  # G1: .*ankle_roll_link
    feet_slip:          {weight: 0.5, tolerance: 0.0, enabled: true, body_names: ankle_roll_.*_link}                  # G1: .*ankle_roll_link
    feet_air_time:      {weight: 3.0, enabled: true, body_names: ankle_roll_.*_link, thres: 0.4, max_air_time: 1.5, soft_discount: 1.0, log_air_time: true}   # G1: .*ankle_roll_link
    survival:           {weight: 1.0, enabled: true}
  
  debug:
    feet_air_time:      {weight: 3.0, enabled: false, body_names: ankle_roll_.*_link, thres: 0.2, soft_discount: 1.0} # G1: .*ankle_roll_link
    feet_contact_count: {weight: 1.0, enabled: false, body_names: ankle_roll_.*_link}                                 # G1: .*ankle_roll_link
    joint_pos_limits:   {weight: 1.0, enabled: false, soft_factor: 0.9, joint_names: .*}
    eef_contact_all:    {weight: 1.0, enabled: false, frc_thres: 1.0, pos_thres: 0.1}
    root_pos_error(keypoint_pos_error):             {body_names: ["pelvis"], weight: 1.0, enabled: false}   # G1: pelvis
    root_ori_error(keypoint_ori_error):             {body_names: ["pelvis"], weight: 1.0, enabled: false}   # G1: pelvis
    body_pos_error_local(keypoint_pos_error_local): {body_names: ["hip_pitch_.*_link", "knee_pitch_.*_link", "ankle_roll_.*_link", "shoulder_pitch_.*_link", "elbow_yaw_.*_link", "wrist_roll_.*_link"], weight: 1.0, enabled: false}   # G1: ".*_hip_pitch_link", ".*_knee_link", ".*_ankle_roll_link", ".*_shoulder_pitch_link", ".*_elbow_link", ".*_wrist_yaw_link"
    body_ori_error_local(keypoint_ori_error_local): {body_names: ["hip_pitch_.*_link", "knee_pitch_.*_link", "ankle_roll_.*_link", "shoulder_pitch_.*_link", "elbow_yaw_.*_link", "wrist_roll_.*_link"], weight: 1.0, enabled: false}   # G1: ".*_hip_pitch_link", ".*_knee_link", ".*_ankle_roll_link", ".*_shoulder_pitch_link", ".*_elbow_link", ".*_wrist_yaw_link"
    joint_pos_error:             {joint_names: ["body_yaw_joint", "hip_.*_joint", "knee_pitch_.*_joint", "shoulder_.*_joint", "elbow_pitch_.*_joint"], weight: 1.0, enabled: false}                                                       # G1: "waist_.*_joint", ".*_hip_.*_joint", ".*_knee_joint", ".*_shoulder_.*_joint", ".*_elbow_joint"

# Common Randomization section
randomization:
  perturb_body_mass:
    .*: [0.9, 1.1]

  perturb_body_materials:
    body_names: ["ankle_roll_.*_link", "wrist_roll_.*_link"]    # G1: ".*ankle_roll_link", ".*_wrist_yaw_link"
    static_friction_range: [0.3, 1.6]
    dynamic_friction_range: [0.3, 1.2]
    restitution_range: [0.0, 0.2]

  perturb_body_com:
    body_names: ["pelvis", "body_yaw_link"]                     # G1: "pelvis", "torso_link"
    com_range: [-0.02, 0.02]

  random_joint_offset:
    .*: [-0.01, 0.01]

# Common Termination section
termination:
  cum_body_pos_error:       {body_names: "body_yaw_link",  min_steps: 25, threshold: 0.5}  # G1: torso_link
  cum_body_ori_error:       {body_names: "body_yaw_link",  min_steps: 25, threshold: 1.2}  # G1: torso_link

  cum_body_pos_error_local: {body_names: ".*",  min_steps: 25, threshold: 0.5}
  cum_body_ori_error_local: {body_names: ".*",  min_steps: 25, threshold: 1.2}

  cum_object_pos_error:     {min_steps: 25, threshold: 0.5}
  cum_object_ori_error:     {min_steps: 25, threshold: 0.8}

  cum_lost_contact_steps:   {min_steps: 25, pos_thres: 0.2, frc_thres: 1.0}
